/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIpackage;

/**
 *
 * @author Owner
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class addinterest extends javax.swing.JFrame {

    /**
     * Creates new form addinterest
     */
    String email;
    String username;
    String user_gender;
    
    public addinterest(String email,String username,String user_gender) {
        this.email=email;
        this.username=username;
        this.user_gender=user_gender;
        initComponents();
        this.setLocationRelativeTo(null);
        findfriend.setBackground(new Color(0,0,0,0));
        leftarrow.setBackground(new Color(0,0,0,0));
        rightarrow.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        leftarrow = new javax.swing.JButton();
        findfriend = new javax.swing.JButton();
        rightarrow = new javax.swing.JButton();
        enterinterest = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        interest = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        coordinate = new javax.swing.JLabel();
//        About = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        close.setFont(new java.awt.Font("Arial Black", 0, 40)); // NOI18N
        close.setText("X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        min.setFont(new java.awt.Font("Arial Black", 0, 40)); // NOI18N
        min.setText("—");
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });

        leftarrow.setBackground(new java.awt.Color(52, 152, 219));
        leftarrow.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        leftarrow.setForeground(new java.awt.Color(255, 255, 255));
        leftarrow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leftarrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftarrowActionPerformed(evt);
            }
        });

        findfriend.setBackground(new java.awt.Color(52, 152, 219));
        findfriend.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        findfriend.setForeground(new java.awt.Color(255, 255, 255));
        findfriend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        findfriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findfriendActionPerformed(evt);
            }
        });

        rightarrow.setBackground(new java.awt.Color(52, 152, 219));
        rightarrow.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rightarrow.setForeground(new java.awt.Color(255, 255, 255));
        rightarrow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rightarrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightarrowActionPerformed(evt);
            }
        });

        enterinterest.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        enterinterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterinterestActionPerformed(evt);
            }
        });

        Name.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        String [] user_array = username.split(" ");
        String [] user_capitalise = new String[user_array.length];
        for(int i=0;i<user_array.length;i++){
            if(user_array.length==1)
                break;
            String uppercaseletter = user_array[i].substring(0,1).toUpperCase();
            user_capitalise[i] = uppercaseletter + user_array[i].substring(1);
        }
        String full_username = "";
        for(int i=0;i<user_array.length;i++){
         full_username += user_capitalise[i] + " ";   
        }
        Name.setText("Username: "+full_username);

        gender.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        gender.setText("Gender: "+user_gender);

        interest.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        interest.setForeground(new java.awt.Color(102, 102, 102));
        
        interest.setText("Interests: "+getInterest(getSpecialID(email,username)));
        

        add.setBackground(new java.awt.Color(255, 255, 204));
        add.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add.setText("Add interest");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        coordinate.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        coordinate.setText("coordinate");

//        About.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
//        About.setText("About XXX");

        bg.setIcon(new javax.swing.ImageIcon("interest.jpg")); // NOI18N
        bg.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1660, 1660, 1660)
                .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1050, 1050, 1050)
                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(leftarrow, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coordinate, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addComponent(About, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(640, 640, 640)
                .addComponent(rightarrow, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(interest, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(enterinterest, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(690, 690, 690)
                .addComponent(findfriend, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftarrow, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(coordinate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
//                        .addComponent(About, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rightarrow, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(interest, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterinterest, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(findfriend, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String getInterest(String specialID){
        String interests = "";
        try{
            String url = "jdbc:mysql://34.87.155.63:3306/friendzone?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection conn = DriverManager.getConnection(url, "root", "password");
            Statement query = conn.createStatement();
            ResultSet rs = query.executeQuery("SELECT interest FROM interestexample WHERE specialid = '"+specialID+"';");
            while ( rs.next() ) {
                String interest = rs.getString("interest");
                String uppercaseLetter = interest.substring(0,1).toUpperCase();
                String uppercaseInterest = uppercaseLetter + interest.substring(1);
                interests += uppercaseInterest+",";
            }
            conn.close();
        }catch(Exception e){
            System.out.println("Error!");
        }
        
        if(interests.length()!=0){
        StringBuilder minat = new StringBuilder(interests);
        minat.deleteCharAt(interests.length()-1);
        return minat.toString();
        }else
            return "";
    }

    private void findfriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findfriendActionPerformed
        // TODO add your handling code here:
//        chat f=new chat();
//        f.setVisible(true);
//        f.pack();
//        f.setLocationRelativeTo(null);
//        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        this.dispose();

    }//GEN-LAST:event_findfriendActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void leftarrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftarrowActionPerformed
        // TODO add your handling code here:
        String usertag = getLeftTag(email,getSpecialID(email,username));
        if(usertag.length()==1){
            String new_username = getUsername(usertag);
            addinterest c=new addinterest(email,new_username,user_gender);
            c.setVisible(true);
            c.pack();
            c.setLocationRelativeTo(null);
            c.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_leftarrowActionPerformed
    
    public String getUsername(String usertag){
        String username = "";
        try{
            String url = "jdbc:mysql://34.87.155.63:3306/friendzone?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection conn = DriverManager.getConnection(url, "root", "password");
            Statement query = conn.createStatement();
            ResultSet rs = query.executeQuery("SELECT username FROM signupuser WHERE email = '"+email+"' AND usertag = '"+usertag+"';");
            while ( rs.next() ) {
                username = rs.getString("username");
            }
            conn.close();
        }catch(Exception e){
            System.out.println("Error!");
        }
        return username;
    }
    
    public String getLeftTag(String email, String specialID){
        String usertag = "";
         try{
            String url = "jdbc:mysql://34.87.155.63:3306/friendzone?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection conn = DriverManager.getConnection(url, "root", "password");
            Statement query = conn.createStatement();
            ResultSet rs = query.executeQuery("SELECT usertag FROM signupuser WHERE email = '"+email+"' AND specialid = '"+specialID+"';");
            while ( rs.next() ) {
                usertag = rs.getString("usertag");
            }
            conn.close();
        }catch(Exception e){
            System.out.println("Error!");
        }
         
         if(!usertag.equals("A")){
             char tag = (char)(usertag.charAt(0) - 1);
             usertag = Character.toString(tag);
             return usertag;
         }
         else
             return "Usertag is not valid";
    }

    private void rightarrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightarrowActionPerformed
        // TODO add your handling code here:
        String usertag = getRightTag(email,getSpecialID(email,username));
        if(usertag.length()==1){
            String new_username = getUsername(usertag);
            addinterest c=new addinterest(email,new_username,user_gender);
            c.setVisible(true);
            c.pack();
            c.setLocationRelativeTo(null);
            c.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_rightarrowActionPerformed
    
    public String getRightTag(String email, String specialID){
        String usertag = "";
         try{
            String url = "jdbc:mysql://34.87.155.63:3306/friendzone?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection conn = DriverManager.getConnection(url, "root", "password");
            Statement query = conn.createStatement();
            ResultSet rs = query.executeQuery("SELECT usertag FROM signupuser WHERE email = '"+email+"' AND specialid = '"+specialID+"';");
            while ( rs.next() ) {
                usertag = rs.getString("usertag");
            }
            conn.close();
        }catch(Exception e){
            System.out.println("Error!");
        }
         
         if(!usertag.equals("Z")){
             char tag = (char)(usertag.charAt(0) + 1);
             usertag = Character.toString(tag);
             return usertag;
         }
         else
             return "Usertag is not valid";
    }

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        addInterest(getSpecialID(email,username));
    }//GEN-LAST:event_addActionPerformed

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void enterinterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterinterestActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_enterinterestActionPerformed
    
    public String getSpecialID(String email,String username){
        String specialID = "";
         try{
            String url = "jdbc:mysql://34.87.155.63:3306/friendzone?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection conn = DriverManager.getConnection(url, "root", "password");
            Statement query = conn.createStatement();
            ResultSet rs = query.executeQuery("SELECT specialid FROM signupuser WHERE email = '"+email+"' AND username = '"+username+"';");
            while ( rs.next() ) {
                specialID = rs.getString("specialid");
            }
            conn.close();
        }catch(Exception e){
            System.out.println("Error!");
        }
         return specialID;
    }
    
    public void addInterest(String specialID){
         try{
            String url = "jdbc:mysql://34.87.155.63:3306/friendzone?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection con = DriverManager.getConnection(url, "root", "password");
            Statement query = con.createStatement();
            query.executeUpdate("INSERT INTO interestexample (specialid,interest) VALUES('"+specialID+"', '"+enterinterest.getText()+"');");

            con.close();
        }catch(Exception e){
            System.out.println("Error!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addinterest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addinterest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addinterest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addinterest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String email = "";
                String password = "";
                String user_gender = "";
                new addinterest(email,password,user_gender).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About;
    private javax.swing.JLabel Name;
    private javax.swing.JButton add;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel close;
    private javax.swing.JLabel coordinate;
    private javax.swing.JTextField enterinterest;
    private javax.swing.JButton findfriend;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel interest;
    private javax.swing.JButton leftarrow;
    private javax.swing.JLabel min;
    private javax.swing.JButton rightarrow;
    // End of variables declaration//GEN-END:variables
}






